version: "3.9"

services:

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clubs
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - project-net

  api:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DATABASE_HOST: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: clubs
    depends_on:
      - postgres
    networks:
      - project-net
    ports:
      - "12000:3000"

networks:
  project-net:

volumes:
  postgres_data: