version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: clubs-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clubs
    ports:
      - "5432:5432"